// src/electron/constants.ts

export const CHANNEL = {
    OPEN_EDITOR_AND_CLOSE_STARTER: 'OPEN_EDITOR_AND_CLOSE_STARTER',
    SELECT_DIRECTORY: 'SELECT_DIRECTORY',
    SELECT_DIRECTORY_REPLY: 'SELECT_DIRECTORY_REPLY',
    SEND_PROJECT_DIR: 'SEND_PROJECT_DIR',
    CONSOLE: 'CONSOLE',
};

